### PR TITLE
Added defaults and negative indices and NR

### PR DESCRIPTION
**Pull request by quintesse**
Added "safe" versions of `s()`, `i()` and `d()` that will not throw any exceptions but will return the specified default value instead.
Added the possibility to specify negative indices indicating indicating access to fields counting back from the end.
Added nr like AWK's NR for Number of Record.

### CODE REVIEW

**Comment by quintesse** [comment]
Thought these would make a couple of nice additions :-)
Untested!

**Comment by evacchi** [comment]
I picked this commit and merged into my catalog as well! https://github.com/evacchi/jbang-catalog/commit/f5b753546f5bf63279552738b4df31ceecb68bce

**Comment by quintesse** [comment]
@evacchi cool! I had actually thought to look at your copy TBH, but it was late and couldn't find your version that quick. We should perhaps create an "official" version @jbangdev? It's really useful IMO.

**Comment by evacchi** [comment]
I am all for making it official! 🚀

**Comment by quintesse** [comment]
In the mean time, here's another 33db143e7368e91b9475aa6deaafc432cd6042f9

**Comment by quintesse** [comment]
Out of curiosity, what's the reasoning behind calling it Prelude? :-)

**Comment by evacchi** [comment]
> Out of curiosity, what's the reasoning behind calling it Prelude? :-)

Prelude is often the name for the standard library that gets auto-imported into the REPL of some languages. Haskell's GHCi is the first that comes to mind (it may also be the one that originated the name, I can't find references for that). The Prelude often comes with useful aliases and shorthands for common operations, so that you don't have to import them explicitly, but you will often have to explicitly import them outside the REPL, in a "traditional" program

https://hackage.haskell.org/package/Prelude-0.1.0.1/docs/Prelude.html

**Comment by quintesse** [comment]
Aha! I understand. So perhaps in this case we should come up with a different name? "jawk" perhaps :-)

**Comment by evacchi** [comment]
I am not strongly opinionated about the name :P

**Comment by quintesse** [comment]
And how about this: 8398e7d970445cada4df00cc338a5b9c4f0ea6d3 . It introduces support for FS, but it also makes a breaking change because I turned public fields into methods. But it makes this possible:

```
cat /etc/passwd | jbang -s prelude.jsh -c '$$(l -> l.fs(":").s(3))'
```

Which would print out all the OIDs in the password file.

**Comment by evacchi** [comment]
this is currently possible (albeit slightly more verbose) with:

```
lines().map(s -> new Line(s, ":")).map(...)
```

something more awk-like, may be:

```
$begin().fs(":").do((l -> l.s(3))
```

where `$begin()` may create some `LineBuilder` and `do` is ~equivalent to `build() + $$()`

```
LineBuilder $begin() { return new LineBuilder(); }
class LineBuilder {
   private String fs = "\s+"; // default
   LineBuilder fs(String pattern) { this.fs = pattern; return this; }
   void do(Function<Line, Object> f) { lines().map(s -> new Line(fs, s)).map(f).forEach(o -> println(o))); }
} 

```

**Comment by quintesse** [comment]
> this is currently possible (albeit slightly more verbose) with:
> 
> ```
> lines().map(s -> new Line(s, ":")).map(...)
> ```

RIght, I found that a little verbose and not very AWK-ish

> 
> something more awk-like, may be:
> 
> ```
> $begin().fs(":").do((l -> l.s(3))
> ```

That's also a nice idea.
I actually thought of having a toplevel `fs()`, which could be used to set the default FS value. The advantage of the `fs()` method on `Line` is that you can change it on-the-fly. (Some of the AWK examples I saw do so as well, so I wanted to enable that too)

**Comment by maxandersen** [comment]
completely missed this one - merging :)

**Pull request merged**
